export const bibleUrl = (passage: string) => `https://www.biblegateway.com/passage/?search=${encodeURIComponent(passage)}&version=KJV`;
export const chapters = [
  ['Jesus revealed','John meets the risen Jesus and receives a message for the churches.','john-angel'],
  ['Listen to the churches','Jesus addresses Ephesus, Smyrna, Pergamos and Thyatira.','ministry'],
  ['An invitation to overcome','Messages to Sardis, Philadelphia and Laodicea call for faithfulness.','prophecy-scroll'],
  ['The throne in heaven','John sees heavenly worship centred on God’s throne.','heavenly-ministry'],
  ['The Lamb and the scroll','The slain Lamb is worthy to open the sealed scroll.','cross'],
  ['The seals are opened','The first six seals reveal conflict, suffering and a cry for justice.','final-events'],
  ['A people belonging to God','The sealing of God’s servants and a great multitude before the throne.','millennium'],
  ['Silence, prayer and trumpets','The seventh seal opens, and the first four trumpets sound.','heavenly-ministry'],
  ['The fifth and sixth trumpets','Two further trumpet visions portray distress and call attention to repentance.','final-events'],
  ['The angel and the little book','John receives an open book and a renewed prophetic commission.','prophecy-scroll'],
  ['Witnesses and the seventh trumpet','The two witnesses testify; the seventh trumpet announces God’s kingdom.','prophecy-scroll'],
  ['The woman and the dragon','A heavenly conflict unfolds around the woman, her child and her offspring.','final-events'],
  ['Two beasts and a choice','Two beasts demand allegiance, bringing worship and loyalty into focus.','symbol-fourth-beast'],
  ['The Lamb and three messages','The Lamb’s people, three angelic messages and the harvest of the earth.','second-coming'],
  ['A song before the plagues','Those victorious over the beast sing; seven angels prepare for judgment.','heavenly-ministry'],
  ['The seven last plagues','Seven bowls are poured out in a vision of judgment.','final-globe'],
  ['The woman and the beast','An angel explains the mystery of Babylon and the beast.','babylon'],
  ['Babylon falls','A call to leave Babylon is followed by lament over her fall.','babylon'],
  ['The returning King','Heaven rejoices, and the faithful and true Rider appears.','second-coming'],
  ['The thousand years','The millennium, final judgment and the end of death.','millennium'],
  ['All things made new','A new heaven, a new earth and the holy city: God dwells with His people.','new-earth'],
  ['The river of life','Life restored, a final invitation and the promise of Jesus’ return.','new-earth'],
] as const;
export const verses = [
'The Revelation of Jesus Christ, which God gave unto him, to shew unto his servants things which must shortly come to pass; and he sent and signified it by his angel unto his servant John:',
'Who bare record of the word of God, and of the testimony of Jesus Christ, and of all things that he saw.',
'Blessed is he that readeth, and they that hear the words of this prophecy, and keep those things which are written therein: for the time is at hand.',
'John to the seven churches which are in Asia: Grace be unto you, and peace, from him which is, and which was, and which is to come; and from the seven Spirits which are before his throne;',
'And from Jesus Christ, who is the faithful witness, and the first begotten of the dead, and the prince of the kings of the earth. Unto him that loved us, and washed us from our sins in his own blood,',
'And hath made us kings and priests unto God and his Father; to him be glory and dominion for ever and ever. Amen.',
'Behold, he cometh with clouds; and every eye shall see him, and they also which pierced him: and all kindreds of the earth shall wail because of him. Even so, Amen.',
'I am Alpha and Omega, the beginning and the ending, saith the Lord, which is, and which was, and which is to come, the Almighty.',
'I John, who also am your brother, and companion in tribulation, and in the kingdom and patience of Jesus Christ, was in the isle that is called Patmos, for the word of God, and for the testimony of Jesus Christ.',
'I was in the Spirit on the Lord’s day, and heard behind me a great voice, as of a trumpet,',
'Saying, I am Alpha and Omega, the first and the last: and, What thou seest, write in a book, and send it unto the seven churches which are in Asia; unto Ephesus, and unto Smyrna, and unto Pergamos, and unto Thyatira, and unto Sardis, and unto Philadelphia, and unto Laodicea.',
'And I turned to see the voice that spake with me. And being turned, I saw seven golden candlesticks;',
'And in the midst of the seven candlesticks one like unto the Son of man, clothed with a garment down to the foot, and girt about the paps with a golden girdle.',
'His head and his hairs were white like wool, as white as snow; and his eyes were as a flame of fire;',
'And his feet like unto fine brass, as if they burned in a furnace; and his voice as the sound of many waters.',
'And he had in his right hand seven stars: and out of his mouth went a sharp twoedged sword: and his countenance was as the sun shineth in his strength.',
'And when I saw him, I fell at his feet as dead. And he laid his right hand upon me, saying unto me, Fear not; I am the first and the last:',
'I am he that liveth, and was dead; and, behold, I am alive for evermore, Amen; and have the keys of hell and of death.',
'Write the things which thou hast seen, and the things which are, and the things which shall be hereafter;',
'The mystery of the seven stars which thou sawest in my right hand, and the seven golden candlesticks. The seven stars are the angels of the seven churches: and the seven candlesticks which thou sawest are the seven churches.',
];
