import RevelationLectureSeries from './lecture-series';
import { SymbolLinks } from './symbol-guide';
import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { FiArrowRight, FiBookOpen, FiCompass, FiSun } from 'react-icons/fi';
import { chapters } from './data';
import StoryMap, { chapterPlace } from './story-map';
export const metadata:Metadata={title:'The Book of Revelation | RevelationSigns',description:'Explore Revelation in Bible chapter order, beginning with an illustrated guide to John’s vision of Jesus.'};
export default function RevelationPage(){return <main>
<section className="rv-hero rv-shell"><div><p className="rv-eyebrow">A guided journey · 22 chapters · One living hope</p><h1>The Book of<br/><em>Revelation</em></h1><p className="rv-lead">Discover Jesus.<br/>Understand the symbols.<br/>Follow the story.</p><p className="rv-muted">Start with Jesus. Read a little at a time. Pictures and simple explanations will help you follow the story.</p><div className="rv-actions"><Link className="rv-button" href="/revelation/chapter-1">Begin with Chapter 1 <FiArrowRight/></Link><a className="rv-text-link" href="#chapter-journey">Explore the chapters ↓</a></div></div><figure><Image src="/media/images/revelation/john-patmos.webp" alt="Illustration of John on the rocky shore of Patmos, looking toward light over the sea" width={1536} height={1024} priority/><figcaption>Patmos, the island John names in Revelation 1:9. An artistic reconstruction.</figcaption></figure></section>
<SymbolLinks/>
<StoryMap/>
<section className="rv-start rv-shell" aria-labelledby="start-title"><div><p className="rv-eyebrow">Start here</p><h2 id="start-title">A book to explore,<br/>one step at a time.</h2></div><div className="rv-start-points"><article><FiBookOpen aria-hidden/><div><h3>Follow your Bible</h3><p>We keep chapters 1–22 in their biblical order. Begin with the passage before exploring its meaning.</p></div></article><article><FiCompass aria-hidden/><div><h3>What do the pictures mean?</h3><p>A symbol is a picture with a meaning. We look for clues in Revelation and in other parts of the Bible.</p></div></article><article><FiSun aria-hidden/><div><h3>Keep the hope in view</h3><p>The opening chapter introduces the risen Jesus; the closing chapters look toward life with God.</p></div></article></div></section>
<section className="rv-shell rv-journey" id="chapter-journey"><p className="rv-eyebrow">The chapter journey</p><h2>From John’s vision to the New Earth.</h2><p className="rv-section-intro">All 22 chapters include the Bible passage, illustrated themes, symbol explanations and reflection questions. The artwork below introduces themes rather than reproducing every detail of each vision.</p><div className="rv-chapters">{chapters.map(([title,description,art],i)=><article id={`chapter-${i+1}`} key={title} className={i===0?'rv-chapter rv-featured':'rv-chapter'}><Image src={i===0?'/media/images/revelation/john-patmos.webp':`/media/images/daniel-revelation/${art}.webp`} alt="" width={960} height={640} sizes="(max-width: 650px) 90vw, (max-width: 1000px) 45vw, 30vw"/><div><p className="rv-eyebrow">Chapter {i+1}{i===0?' · Start here':''}</p><h3>{title}</h3><span className="rv-chapter-time">{chapterPlace(i+1).time}</span><p>{description}</p><Link href={`/revelation/chapter-${i+1}`}>Open the illustrated study <FiArrowRight/></Link></div></article>)}</div></section>
<section className="rv-shell rv-connection"><div><p className="rv-eyebrow">See the wider picture</p><h2>How does Revelation connect with Daniel?</h2><p>Explore our existing illustrated overview of kingdoms, the Messiah and the heavenly messengers. Its historical identifications follow a historicist interpretation, which reads prophecy across the course of history.</p><Link className="rv-button" href="/daniel-revelation#grand-timeline">Explore the Daniel &amp; Revelation overview <FiArrowRight/></Link></div><Image src="/media/images/daniel-revelation/new-earth.webp" alt="Conceptual illustration of the New Earth and restored life" width={960} height={640}/></section>
<RevelationLectureSeries/>
</main>}
