import Image from 'next/image';
import Link from 'next/link';
export const storySteps = [
 {title:'John meets Jesus',time:'John’s time · first century',chapters:'Chapters 1–3',first:1,last:3,art:'john-angel',text:'Jesus gives John a message for His churches.'},
 {title:'God cares for His people',time:'Through history toward the end',chapters:'Chapters 4–14',first:4,last:14,art:'prophecy-scroll',text:'Different visions show the struggle between good and evil.'},
 {title:'Evil faces judgment',time:'The closing events',chapters:'Chapters 15–18',first:15,last:18,art:'final-globe',text:'God judges evil. Babylon’s power comes to an end.'},
 {title:'Jesus returns',time:'The Second Coming',chapters:'Chapter 19',first:19,last:19,art:'second-coming',text:'Jesus comes as King. Evil cannot defeat Him.'},
 {title:'Evil ends for ever',time:'The 1,000 years and final judgment',chapters:'Chapter 20',first:20,last:20,art:'millennium',text:'After the thousand years, death and evil meet their end.'},
 {title:'God makes all things new',time:'Life with God for ever',chapters:'Chapters 21–22',first:21,last:22,art:'new-earth',text:'God lives with His people. There is no more death or pain.'},
];
export function chapterPlace(chapter:number){return storySteps.find(step=>chapter>=step.first&&chapter<=step.last)!;}
export default function StoryMap({chapter}:{chapter?:number}){
 const current=chapter?chapterPlace(chapter):null;
 return <section className="rv-story-map rv-shell" aria-labelledby="story-map-title"><p className="rv-eyebrow">Your guide through the story</p><h2 id="story-map-title">Where are we in the story?</h2><p className="rv-map-intro">Start with John. Follow the story through history to Jesus’ return and a world made new.</p>{current&&<div className="rv-you-are-here"><strong>You are here: Chapter {chapter} · {current.title}</strong><p>{chapter===1?'John is on Patmos in the first century, long before our time. He meets the risen Jesus, who shows him what lies ahead.':current.text}</p><span>{chapter===1?'Next in our study: Jesus’ messages to the churches in Chapter 2.':current.time}</span></div>}<ol className="rv-map-track">{storySteps.map((step,i)=><li key={step.title} className={current===step?'rv-map-current':''}><Link href={`/revelation#chapter-${step.first}`} aria-current={current===step?'step':undefined}><div className="rv-map-picture"><Image src={i===0?'/media/images/revelation/john-patmos.webp':`/media/images/daniel-revelation/${step.art}.webp`} alt="" width={960} height={640} sizes="(max-width:650px) 42vw, 180px"/><span>{i+1}</span></div><div className="rv-map-copy"><span className="rv-map-position">{current===step?'You are here':step.time}</span><h3>{step.title}</h3><p>{step.text}</p><strong>{step.chapters} →</strong></div></Link></li>)}</ol><div className="rv-map-help"><strong>One important thing to remember</strong><p>Some visions go back and show the same time again, with more detail—like looking at the same story from another side. So a later chapter does not always mean a later event.</p><details><summary>About this timeline</summary><p>This is a simple guide to the main themes, not a list of exact dates. {chapter === 13 ? 'It follows this study’s reading of prophecy across history.' : 'It follows our historicist interpretation: a way of reading prophecy across history.'} Some chapters look back or give a glimpse of the ending before returning to the story. Christians differ on how these visions fit into history.</p><a href="https://adventistbiblicalresearch.org/articles/recapitulation-in-revelation-4-11" target="_blank" rel="noreferrer">Read more about repeated visions (Biblical Research Institute) ↗</a></details></div></section>
}
