import Image from 'next/image';
import { bibleUrl } from './data';
const examples = [
 {art:'lampstands',alt:'Cinematic illustration of seven golden lampstands with a church community gathered behind them',picture:'Seven lampstands',meaning:'Seven churches',verse:'Revelation 1:20',quote:'the seven candlesticks which thou sawest are the seven churches.',help:'“Candlesticks” is the KJV word used here for lampstands.'},
 {art:'stars',alt:'Cinematic illustration of seven bright stars above a hillside of church gathering places',picture:'Seven stars',meaning:'The angels of the seven churches',verse:'Revelation 1:20',quote:'The seven stars are the angels of the seven churches',help:'The verse gives this meaning. Who these angels are is a further question to study.'},
 {art:'dragon',alt:'Cinematic illustration of a red dragon on a rocky hill, representing the enemy in the vision',picture:'The dragon',meaning:'The Devil, or Satan',verse:'Revelation 12:9',quote:'that old serpent, called the Devil, and Satan',help:'The verse names the enemy pictured by the dragon.'},
 {art:'waters',alt:'Cinematic illustration linking blue waters with a crowd of people from many nations',picture:'The waters in this vision',meaning:'Peoples, nations and languages',verse:'Revelation 17:15',quote:'are peoples, and multitudes, and nations, and tongues.',help:'“Tongues” means languages here. Read the whole verse to see which waters it explains.'},
];
export default function SymbolGuide({compact=false}:{compact?:boolean}){return <section className="rv-symbol-guide rv-shell" id="bible-symbols" aria-labelledby="bible-symbols-title"><p className="rv-eyebrow">Before you begin · The Bible explains the Bible</p><h2 id="bible-symbols-title">Let the Bible explain the symbols.</h2><p className="rv-guide-intro">A symbol is a picture that stands for something. We do not need to guess: first, look for a verse that explains it.</p><ol className="rv-reading-steps"><li><strong>1. See the picture</strong><span>What does John see?</span></li><li><strong>2. Read the explanation</strong><span>What does the Bible say it means?</span></li><li><strong>3. Read around it</strong><span>How does it fit this part of the story?</span></li></ol><div className="rv-symbol-examples">{examples.slice(0,compact?2:4).map(item=><article key={item.picture}><Image className="rv-symbol-art" src={`/media/images/revelation/symbol-${item.art}-realistic.webp`} alt={item.alt} width={1536} height={1024} sizes="(max-width:650px) 92vw, 580px"/><div className="rv-symbol-story"><span className="rv-label">Picture → Meaning</span><h3>{item.picture}</h3><p className="rv-symbol-meaning">{item.meaning}</p><blockquote>“{item.quote}”</blockquote><a className="rv-reference" href={bibleUrl(item.verse)} target="_blank" rel="noreferrer">{item.verse} · KJV ↗<span className="rv-sr-only"> (opens in a new tab)</span></a><p className="rv-symbol-help">{item.help}</p></div></article>)}</div>{compact?<p className="rv-guide-note">These two pictures are explained in this chapter. <a href="/revelation#bible-symbols">See more examples in the symbol guide →</a></p>:<details className="rv-extra-example"><summary>One more example: the beasts in Daniel’s vision</summary><Image className="rv-beast-example" src="/media/images/daniel-revelation/symbol-lion.webp" alt="Illustration of a winged lion, one of the animals in Daniel’s vision" width={720} height={480}/><p>Daniel 7:17 calls the four beasts four kings. Verse 23 calls the fourth beast a fourth kingdom. The chapter helps us connect the picture of a beast with a ruling power.</p><a className="rv-reference" href={bibleUrl('Daniel 7:17,23')} target="_blank" rel="noreferrer">Read Daniel 7:17,23 · KJV ↗<span className="rv-sr-only"> (opens in a new tab)</span></a></details>}<p className="rv-guide-note"><strong>Keep the verse beside the picture.</strong> A symbol can have a different meaning in another passage. If the Bible does not explain it directly, we will show the verses we compare and clearly say when we are giving an interpretation.</p></section>}
