import Image from 'next/image';
import { bibleUrl } from './data';
const examples = [
 {art:'lampstands',alt:'Cinematic illustration of seven golden lampstands with a church community gathered behind them',picture:'Seven lampstands',meaning:'Seven churches',verse:'Revelation 1:20',quote:'the seven candlesticks which thou sawest are the seven churches.',help:'These were seven real church communities: Ephesus, Smyrna, Pergamos, Thyatira, Sardis, Philadelphia and Laodicea. Read their messages in Revelation 2–3. “Candlesticks” means lampstands.'},
 {art:'stars',alt:'Cinematic illustration of seven bright stars above a hillside of church gathering places',picture:'Seven stars',meaning:'The angels of the seven churches',verse:'Revelation 1:20',quote:'The seven stars are the angels of the seven churches',help:'The verse gives this meaning. Who these angels are is a further question to study.'},
 {art:'dragon',alt:'Cinematic illustration of a red dragon on a rocky hill, representing the enemy in the vision',picture:'The dragon',meaning:'The Devil, or Satan',verse:'Revelation 12:9',quote:'that old serpent, called the Devil, and Satan',help:'The verse names the enemy pictured by the dragon.'},
 {art:'waters',alt:'Cinematic illustration linking blue waters with a crowd of people from many nations',picture:'The waters in this vision',meaning:'Peoples, nations and languages',verse:'Revelation 17:15',quote:'are peoples, and multitudes, and nations, and tongues.',help:'“Tongues” means languages here. Read the whole verse to see which waters it explains.'},
 {art:'woman-sun',alt:'A woman clothed in sunlight, with the moon beneath her feet and a crown of stars',picture:'The woman clothed with the sun',meaning:'A picture of God’s faithful people',verse:'Revelation 12:1–6,17; Genesis 37:9–10',quote:'a woman clothed with the sun, and the moon under her feet',help:'Interpretation from related passages: her child is the Messiah, and her other children keep God’s commandments and hold the testimony of Jesus. The sun, moon and stars also recall Joseph’s dream about Israel.',interpretation:true},
 {art:'woman-babylon',alt:'A woman in purple and scarlet holding a golden cup before an ancient city',picture:'The woman called Babylon',meaning:'The great city that rules over kings',verse:'Revelation 17:4–5,18',quote:'the woman which thou sawest is that great city',help:'The angel directly identifies her as a city. Historicist interpretation also sees an unfaithful religious and political system, often associated with papal Rome. This is an interpretation, not a judgment about individual believers.'},
 {art:'seven-mountains',alt:'Seven mountain peaks across an ancient landscape',picture:'Seven heads · seven mountains',meaning:'Mountains — and also seven kings',verse:'Revelation 17:9–11',quote:'The seven heads are seven mountains',help:'Read the next verse too: the angel also speaks of seven kings. How these kings fit history is interpreted differently; the image alone does not settle that question.'},
 {art:'symbol-horns',folder:'daniel-revelation',alt:'An illustration of prophetic horns representing ruling powers',picture:'Ten horns',meaning:'Ten kings',verse:'Revelation 17:12',quote:'the ten horns which thou sawest are ten kings',help:'A horn can picture a ruler’s power. Here the angel tells us plainly what these ten horns represent.'},
 {art:'symbol-lion',folder:'daniel-revelation',alt:'A winged lion from Daniel’s prophetic vision',picture:'Prophetic beasts',meaning:'Kings and kingdoms in Daniel’s vision',verse:'Daniel 7:17,23; Revelation 13:1–2',quote:'These great beasts, which are four, are four kings',help:'Daniel 7:23 also calls the fourth beast a kingdom. Revelation reuses the lion, bear and leopard imagery. Identifying particular powers requires studying the whole passage.'},
 {art:'new-earth',folder:'daniel-revelation',alt:'An illustration of the beautiful New Jerusalem and people living in peace',picture:'The bride · New Jerusalem',meaning:'The holy city, home with God',verse:'Revelation 21:9–10',quote:'I will shew thee the bride, the Lamb’s wife',help:'The angel then shows John the holy city, New Jerusalem. The picture is about belonging to God and living with Him. Read verses 2–3 as well.'},

 {art:'lamb',alt:'A white lamb in dawn light, with a distant cross',picture:'The Lamb',meaning:'Jesus, who gave His life for us',verse:'John 1:29; Revelation 5:6–9',quote:'Behold the Lamb of God, which taketh away the sin of the world.',help:'John 1:29 names Jesus as the Lamb of God. In Revelation 5, the Lamb was slain and redeems people through His blood.'},
 {art:'incense',alt:'Incense rising from a golden bowl',picture:'Golden bowls of incense',meaning:'The prayers of God’s people',verse:'Revelation 5:8; 8:3–4',quote:'golden vials full of odours, which are the prayers of saints',help:'“Vials” means bowls, and “odours” refers to incense. This picture helps us see that God hears His people when they pray.'},
 {art:'linen',alt:'Clean white linen robes in warm light',picture:'Clean, white linen',meaning:'The righteousness of God’s people',verse:'Revelation 19:8',quote:'the fine linen is the righteousness of saints',help:'The bride is given clean clothing. It pictures the righteous life of God’s people; “saints” means His holy people.'},

];
export default function SymbolGuide({compact=false}:{compact?:boolean}){return <section className="rv-symbol-guide rv-shell" id="bible-symbols" aria-labelledby="bible-symbols-title"><div className="rv-symbol-banner"><p className="rv-eyebrow">Before you begin · The Bible explains the Bible</p><h2 id="bible-symbols-title">Your illustrated guide to Revelation’s symbols.</h2><p className="rv-guide-intro">A symbol is a picture that stands for something. We do not need to guess: first, look for a verse that explains it. Follow the pictures down the page, one at a time.</p></div><ol className="rv-reading-steps"><li><strong>1. See the picture</strong><span>What does John see?</span></li><li><strong>2. Read the explanation</strong><span>What does the Bible say it means?</span></li><li><strong>3. Read around it</strong><span>How does it fit this part of the story?</span></li></ol>{!compact && <nav className="rv-symbol-jumps" aria-label="Find a Bible symbol">{examples.map(item=><a key={item.art} href={`#symbol-${item.art}`}>{item.picture}</a>)}</nav>}<div className="rv-symbol-examples">{(compact ? examples.slice(0,2) : examples).map((item,index)=><article key={item.picture} id={`symbol-${item.art}`}><Image className="rv-symbol-art" src={'folder' in item ? `/media/images/${item.folder}/${item.art}.webp` : `/media/images/revelation/symbol-${item.art}-realistic.webp`} alt={item.alt} width={1536} height={1024} sizes="(max-width:650px) 92vw, 420px"/><div className="rv-symbol-story"><span className="rv-label">{String(index+1).padStart(2,'0')} · {'interpretation' in item ? 'Interpretation from related verses' : 'Picture → Bible explanation'}</span><h3>{item.picture}</h3><p className="rv-symbol-meaning">{item.meaning}</p><blockquote>“{item.quote}”</blockquote><a className="rv-reference" href={bibleUrl(item.verse)} target="_blank" rel="noreferrer">{item.verse} · KJV ↗<span className="rv-sr-only"> (opens in a new tab)</span></a><p className="rv-symbol-help">{item.help}</p></div></article>)}</div>{compact?<p className="rv-guide-note">These two pictures are explained in this chapter. <a href="/revelation#bible-symbols">See more examples in the symbol guide →</a></p>:null}<p className="rv-guide-note"><strong>Keep the verse beside the picture.</strong> These illustrations highlight a symbol; they do not show every detail of each vision. A symbol can have a different meaning in another passage. If the Bible does not explain it directly, we will show the verses we compare and clearly say when we are giving an interpretation.</p></section>}
