import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Roboto_Condensed } from "next/font/google";
import { FiArrowRight, FiChevronDown, FiMenu, FiPlay, FiSearch } from "react-icons/fi";
import { grand, messiah, angels, rows, alt } from "./data";
import "./page.css";

const condensed = Roboto_Condensed({ subsets: ["latin"], display: "swap" });
export const metadata: Metadata = {title:"Daniel & Revelation | RevelationSigns", description:"Discover the history of the world through Daniel and Revelation: a visual journey from Babylon to the New Earth."};
function Art({id,className='',priority=false}:{id:string;className?:string;priority?:boolean}) {
 return <div className={`dr-art ${className}`}><Image src={`/media/images/daniel-revelation/${id}.webp`} alt={alt[id] || ''} fill sizes={id==='hero-panorama' || id==='journey-landscape'?'100vw':'(max-width: 700px) 180px, (max-width: 1100px) 140px, 220px'} priority={priority} className="dr-image" /></div>;
}
function Refs({items}:{items:string[]}){return <span className="dr-refs">{items.map(ref=><a key={ref} href={`https://www.biblegateway.com/passage/?search=${encodeURIComponent(ref)}&version=KJV`} target="_blank" rel="noreferrer" aria-label={`Read ${ref} (opens in a new tab)`}>{ref}</a>)}</span>}
function ResourceLinks(){return <><Link href="/documentaries">Documentaries</Link><Link href="/lecture-series/total-onslaught">Total Onslaught</Link><Link href="/starfall">Starfall</Link><Link href="/great-controversy">The Great Controversy</Link></>}
export default function Page(){return <div className={`dr-page ${condensed.className}`}>
<header className="dr-header"><Link href="/" className="dr-brand" aria-label="RevelationSigns home">Revelation<span>Signs</span><small>Discover · Understand · Be Prepared</small></Link>
<nav className="dr-nav" aria-label="Daniel and Revelation navigation"><Link href="/">Home</Link><Link href="/bible-studies">Bible Studies</Link><Link href="/daniel-revelation" aria-current="page">Daniel &amp; Revelation</Link><Link href="/questions">Questions</Link><details className="dr-resources"><summary>Resources <FiChevronDown/></summary><div><ResourceLinks/></div></details><Link href="/contact">Contact</Link></nav>
<a className="dr-search" href="/questions" aria-label="Search Bible questions"><FiSearch/></a><a href="#grand-timeline" className="dr-button dr-start">Start Exploring <FiArrowRight/></a>
<details className="dr-mobile-menu"><summary aria-label="Open navigation menu"><FiMenu/></summary><nav aria-label="Mobile page navigation"><Link href="/">Home</Link><Link href="/bible-studies">Bible Studies</Link><Link href="/daniel-revelation" aria-current="page">Daniel &amp; Revelation</Link><Link href="/questions">Questions</Link><ResourceLinks/><Link href="/contact">Contact</Link></nav></details>
</header>
<main>
<section className="dr-hero"><div className="dr-hero-copy"><p className="dr-overline">Discover the History of the World</p><h1>Daniel &amp; Revelation</h1><h2>Two Books. One Prophetic Story.</h2><p>Different times. The same God. A revealed future. A certain hope.</p></div><div className="dr-hero-scene"><Art id="hero-panorama" priority/><aside className="dr-quote dr-quote-left"><em>“He revealeth<br/>deep and secret things…”</em><span>Daniel 2:22</span></aside><aside className="dr-quote dr-quote-right"><em>“The Revelation of<br/>Jesus Christ…”</em><span>Revelation 1:1</span></aside></div></section>
<section className="dr-timeline-intro" aria-labelledby="timeline-intro-title"><h2 id="timeline-intro-title">Discover History in Advance</h2><p className="dr-intro-lead">The timeline from Daniel’s visions to Revelation — from ancient Babylon to our days, and beyond.</p><p>Follow the story from left to right. Each stage connects a kingdom or era with a prophetic symbol and a Bible passage, helping you see how this historicist reading connects prophecy with history — and points forward to Christ’s return and the New Earth.</p></section>
<section id="grand-timeline" className="dr-grand"><h2 className="dr-section-bar">The Great Prophecy Timeline <span>— From ancient kingdoms to the New Earth</span></h2><p className="dr-scroll-hint">Scroll sideways to follow all eleven stages →</p><div className="dr-scroll" role="region" aria-label="Great Prophecy Timeline; scroll horizontally to explore all eleven stages" tabIndex={0}><div className="dr-grand-track">{grand.map((item,i)=><article key={item.name} className="dr-grand-item"><a href={`#daniel-${item.id}`} className="dr-stage-image" aria-label={`Explore ${item.name}`}><Art id={item.art}/></a><div className="dr-stage-copy"><a href={`#daniel-${item.id}`}><h3>{item.name}</h3></a><p className={i===5?'dr-interpretation-date':''}>{item.date}</p><p className="dr-stage-symbol">{item.symbol}</p><Refs items={item.refs}/></div></article>)}</div></div></section>
<section className="dr-messiah"><h2 className="dr-section-bar">The Messiah Line <span>— God’s plan of redemption running through history</span></h2><p className="dr-scroll-hint">Scroll sideways to follow the whole Messiah line →</p><div className="dr-scroll" role="region" aria-label="The Messiah Line; scroll horizontally through nine events" tabIndex={0}><div className="dr-messiah-track">{messiah.map(item=><article key={item.name}><Art id={item.art}/><div className="dr-messiah-copy"><h3>{item.name}</h3><Refs items={item.refs}/></div></article>)}</div></div></section>
<section className="dr-angels"><h2>The Angelic Messenger Line <span>— From Daniel to Revelation</span></h2><div className="dr-angel-track">{angels.map((item,i)=><article key={item.name}><Art id={item.art}/><div className="dr-angel-copy"><h3>{item.name}</h3><Refs items={item.refs}/>{i<3&&<FiArrowRight className="dr-angel-arrow" aria-hidden/>}</div></article>)}</div><p className="dr-angel-note">Gabriel is named in Daniel 8–9. Revelation’s angel is unnamed; Scripture does not identify them as the same messenger.</p></section>
<section className="dr-comparison" id="comparison"><div className="dr-comparison-heading"><h2>Daniel and Revelation — Side by Side</h2><p>The kingdoms. The symbols. The conflict. The same glorious hope.</p></div><div className="dr-table-pair">
<div className="dr-table-scroll dr-daniel" role="region" aria-label="Daniel: symbols and their historical meaning" tabIndex={0}><table><caption><strong>Daniel</strong><span>The prophecy given (6th century BC)</span></caption><colgroup><col className="dr-col-name"/><col className="dr-col-art"/><col className="dr-col-meaning"/><col className="dr-col-refs"/></colgroup><thead><tr><th scope="col">Kingdom / Symbol</th><th scope="col">Symbol → History</th><th scope="col">Meaning</th><th scope="col">Key Passages</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id} id={`daniel-${row.id}`}><th scope="row"><div className="dr-row-name"><span className="dr-number">{i+1}</span><div><strong>{row.name}</strong><small>{row.symbol}</small></div></div></th><td className="dr-paired-images"><div><figure><Art id={row.symbolArt}/><figcaption>{i===6?'Scripture':i===7?'Illustration':'Symbol'}</figcaption></figure><figure><Art id={row.history}/><figcaption>{i>6?'Prophecy':'History'}</figcaption></figure></div></td><td><strong>{row.meaning}</strong><span className={row.id==='papal'?'dr-interpretation-date':''}>{row.date}</span><p>{row.detail}</p></td><td><Refs items={row.refs}/></td></tr>)}</tbody></table></div>
<div className="dr-table-scroll dr-revelation" role="region" aria-label="Revelation: corresponding imagery and expanded meaning" tabIndex={0}><table><caption><strong>Revelation</strong><span>The prophecy expanded (1st century AD)</span></caption><colgroup><col className="dr-col-name"/><col className="dr-col-art"/><col className="dr-col-meaning"/><col className="dr-col-refs"/></colgroup><thead><tr><th scope="col">Corresponding Vision</th><th scope="col">Image</th><th scope="col">Expanded Meaning</th><th scope="col">Key Passages</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id}><th scope="row"><div className="dr-row-name"><span className="dr-r-number">{i+1}.</span><strong>{row.rName}</strong></div></th><td className="dr-revelation-image"><Art id={row.rArt}/></td><td><strong>{row.rMeaning}</strong><p>{row.rDetail}</p></td><td><Refs items={row.rRefs}/></td></tr>)}</tbody></table></div>
</div><div className="dr-reading-note"><p><strong>Read the connection carefully.</strong> Revelation 13 combines lion, bear and leopard imagery in one beast; these are echoes of Daniel, not three separate beasts in Revelation. The pictures highlight those connections.</p><p>The medieval papal identification is a <strong>historicist interpretation</strong>; other Christians read these prophecies differently. Dates follow this study’s outline. Historical scenes are artistic reconstructions, and future scenes are illustrations.</p></div></section>
<section className="dr-watch"><Art id="journey-landscape"/><div className="dr-watch-content"><span className="dr-play-emblem" aria-hidden><FiPlay/></span><div><h2>Watch the Full Journey</h2><h3>A cinematic overview</h3><p>From ancient kingdoms to the New Earth — see how it all fits together.</p></div><button type="button" className="dr-button" disabled><FiPlay/> Video Coming Soon</button></div></section>
<div className="dr-study-links"><Link href="/bible-studies/prophecy/daniel-2">Study Daniel in Detail <FiArrowRight/></Link><Link href="/bible-studies/daniel-revelation">Explore Daniel &amp; Revelation Studies <FiArrowRight/></Link></div>
</main><footer className="dr-footer"><p><em>“Surely the Lord GOD will do nothing, but he revealeth his secret unto his servants the prophets.”</em> <span>Amos 3:7</span></p><small>Discover · Understand · Be Prepared</small></footer>
</div>}
