import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata={title:"Daniel & Revelation | RevelationSigns",description:"Discover the history of the world through Daniel and Revelation."};
const prophecy=[["Babylon","605–539 BC","Head of gold","Daniel 2:38"],["Medo-Persia","539–331 BC","Chest of silver","Daniel 2:39"],["Greece","331–168 BC","Bronze","Daniel 2:39"],["Rome","168 BC–AD 476","Iron","Daniel 2:40"],["Divided Rome","AD 476 onward","Feet & toes","Daniel 2:41–43"],["Papal power","Historicist view","Little horn","Daniel 7:8,24–25"],["Reformation","1517 onward","Scripture","Daniel 7"],["Final crisis","End time","Trouble","Daniel 12:1"],["Second Coming","Christ returns","Kingdom","Daniel 2:44"],["Millennium","1,000 years","With Christ","Revelation 20"],["New Earth","Eternity","All things new","Revelation 21–22"]];
const messiah=[["Messiah foretold","Daniel 9:24–27"],["Bethlehem","Micah 5:2"],["Ministry","Luke 4:18–19"],["Cross","Isaiah 53:5"],["Resurrection","Matthew 28:6"],["Heavenly ministry","Hebrews 8:1–2"],["Return in glory","Revelation 19:11–16"],["Resurrection","1 Thessalonians 4:16–17"],["New Earth","Revelation 21–22"]];
const daniel=[["Babylon","Head of gold","Babylonian Empire","Daniel 2:38"],["Medo-Persia","Silver / bear / ram","Medo-Persian Empire","Daniel 2:39; 7:5; 8:3–4"],["Greece","Bronze / leopard / goat","Greek-Macedonian Empire","Daniel 2:39; 7:6; 8:5–8"],["Rome","Iron / fourth beast","Roman Empire","Daniel 2:40; 7:7"],["Divided Rome","Feet, toes / ten horns","Divided kingdoms","Daniel 2:41–43; 7:24"],["Little horn","Different power","Historicist: medieval papal system","Daniel 7:8,20–25"],["Final conflict","Time of trouble","Closing conflict","Daniel 12:1"],["Kingdom of God","Stone / everlasting kingdom","Christ's eternal kingdom","Daniel 2:44–45; 7:13–14"]];
const revelation=[["Churches","Christ among His people","Revelation 1–3"],["Heavenly throne","Worship and judgment","Revelation 4–5"],["Seals","Conflict through history","Revelation 6–8"],["Dragon & beasts","Great controversy","Revelation 12–13"],["Three angels","Final gospel messages","Revelation 14"],["Babylon & final crisis","Worship, allegiance, judgment","Revelation 16–18"],["Christ returns","King of kings","Revelation 19"],["Millennium & New Earth","Judgment, restoration, eternity","Revelation 20–22"]];
export default function Page(){return <main className="min-h-screen bg-[#06101a] text-white pt-[82px]">
<section className="bg-[radial-gradient(circle_at_50%_0%,#17395d,#06101a_72%)] px-5 py-14 text-center"><p className="text-xs font-semibold uppercase tracking-[.28em] text-[#efc86f]">Discover the history of the world — written in prophecy</p><h1 className="mt-3 font-serif text-5xl font-semibold text-[#f5d98f] sm:text-7xl">Daniel &amp; Revelation</h1><p className="mt-2 font-serif text-2xl uppercase tracking-widest">Two Books. One Prophetic Story.</p><p className="mx-auto mt-4 max-w-3xl text-white/70">Different times. The same God. A revealed future. A certain hope.</p></section>
<section className="py-10"><h2 className="text-center font-serif text-3xl text-[#f5d98f]">The Great Prophecy Timeline</h2><p className="mb-7 text-center text-white/60">From ancient kingdoms to the New Earth</p><div className="overflow-x-auto px-4 pb-4"><div className="mx-auto grid min-w-[1500px] max-w-[1600px] grid-cols-11 gap-2">{prophecy.map((x,i)=><article key={x[0]} className="min-h-52 rounded border border-[#d6aa55]/25 bg-gradient-to-b from-[#163653] to-[#091827] p-4"><div className="mb-3 font-serif text-4xl text-[#d9ad55]">{i+1}</div><h3 className="font-serif text-lg font-semibold">{x[0]}</h3><p className="text-xs text-[#efc86f]">{x[1]}</p><p className="mt-4 text-sm">{x[2]}</p><p className="mt-2 text-xs text-white/50">{x[3]}</p></article>)}</div></div></section>
<section className="bg-[#f3ead8] py-10 text-[#17202b]"><h2 className="text-center font-serif text-3xl font-semibold">The Messiah Line</h2><p className="mb-8 text-center">God's plan of redemption running through history</p><div className="mx-auto grid max-w-[1500px] gap-3 px-5 md:grid-cols-3 xl:grid-cols-9">{messiah.map(x=><div key={x[0]} className="rounded-lg bg-white/70 p-4 text-center"><div className="mx-auto mb-3 h-3 w-3 rounded-full bg-[#b78322]"/><p className="font-serif text-lg font-semibold">{x[0]}</p><p className="text-xs">{x[1]}</p></div>)}</div></section>
<section className="border-y border-[#d6aa55]/25 bg-[#0b2034] py-12 text-center"><h2 className="font-serif text-3xl text-[#f5d98f]">The Angelic Messenger Line</h2><p className="mt-2 text-white/60">From Daniel to Revelation — heavenly messengers communicate God's revelation.</p><div className="mx-auto mt-8 grid max-w-[1400px] gap-4 px-5 md:grid-cols-4">{[["Daniel receives the vision","Daniel 8:15–17"],["Gabriel explains","Daniel 8:16; 9:21–23"],["Daniel is strengthened","Daniel 10:10–21"],["John receives Revelation through an angel","Revelation 1:1; 22:6,16"]].map(x=><div key={x[0]} className="rounded-xl border border-[#d6aa55]/25 bg-[#071522] p-6"><div className="text-3xl text-[#efc86f]">✦</div><h3 className="mt-3 font-serif text-xl">{x[0]}</h3><p className="mt-2 text-sm text-white/50">{x[1]}</p></div>)}</div></section>
<section className="py-16"><h2 className="text-center font-serif text-4xl text-[#f5d98f]">Daniel &amp; Revelation — Side by Side</h2><p className="mb-10 text-center text-white/60">Prophecy given. History unfolded. Revelation expands the picture.</p><div className="mx-auto grid max-w-[1550px] gap-7 px-5 lg:grid-cols-2">
<div className="overflow-hidden rounded-xl border border-sky-400/35"><div className="bg-[#0c4b78] p-6 text-center"><h3 className="font-serif text-4xl">Daniel</h3><p>Prophecy given — 6th century BC</p></div>{daniel.map((x,i)=><div key={x[0]} className="grid grid-cols-[76px_1fr] gap-4 border-t border-white/10 bg-[#09243a] p-5"><div className="flex h-20 items-center justify-center rounded-lg bg-gradient-to-br from-[#d9ad55]/40 to-sky-800 text-3xl font-bold">{i+1}</div><div><h4 className="font-serif text-2xl">{x[0]}</h4><p className="text-[#efc86f]">{x[1]}</p><div className="mt-3 rounded-lg bg-black/20 p-3"><p className="text-xs uppercase tracking-widest text-white/40">History / Kingdom</p><p className="mt-1 text-lg font-semibold">{x[2]}</p></div><p className="mt-3 text-xs text-white/50">{x[3]}</p></div></div>)}</div>
<div className="overflow-hidden rounded-xl border border-fuchsia-400/35"><div className="bg-[#55216f] p-6 text-center"><h3 className="font-serif text-4xl">Revelation</h3><p>Prophecy expanded — 1st century AD</p></div>{revelation.map((x,i)=><div key={x[0]} className="grid grid-cols-[76px_1fr] gap-4 border-t border-white/10 bg-[#241638] p-5"><div className="flex h-20 items-center justify-center rounded-lg bg-gradient-to-br from-fuchsia-500/25 to-[#d9ad55]/25 text-3xl font-bold">{i+1}</div><div><h4 className="font-serif text-2xl">{x[0]}</h4><p className="mt-1 text-white/80">{x[1]}</p><p className="mt-3 text-xs text-white/50">{x[2]}</p></div></div>)}</div></div>
<p className="mx-auto mt-7 max-w-4xl px-5 text-center text-sm leading-6 text-white/50">The little-horn identification shown here is the historicist interpretation used in this study. Other Christian schools interpret these passages differently; the detailed study will let readers examine the biblical characteristics and historical evidence.</p></section>
<section className="border-y border-[#d6aa55]/30 bg-[#0b2034] py-12 text-center"><div className="text-5xl">▶</div><h2 className="mt-3 font-serif text-3xl">Watch the Full Journey</h2><p className="mt-2 text-white/60">A cinematic overview from ancient Babylon to the New Earth.</p><span className="mt-6 inline-block rounded bg-[#d9ad55] px-7 py-3 font-semibold text-[#071522]">Cinematic Journey — Coming Later</span></section>
<section className="py-14"><div className="mx-auto grid max-w-5xl gap-5 px-5 md:grid-cols-2"><Link href="/bible-studies" className="rounded-xl border border-sky-400/30 bg-[#0a2942] p-7"><h3 className="font-serif text-2xl text-[#f5d98f]">Study Daniel in Detail →</h3><p className="mt-2 text-sm text-white/60">Explore every chapter, symbol and historical connection.</p></Link><Link href="/bible-studies" className="rounded-xl border border-fuchsia-400/30 bg-[#26163b] p-7"><h3 className="font-serif text-2xl text-[#f5d98f]">Study Revelation Chronologically →</h3><p className="mt-2 text-sm text-white/60">Follow Revelation carefully from chapter 1 through 22.</p></Link></div></section></main>}