"use client";

import Link from "next/link";
import Image from "next/image";
import type { ReactNode } from "react";
import { Footer } from "@/components/layout/Footer";
import { useStudyProgress } from "@/hooks/useStudyProgress";

const prophecies = [
  ["Born in Bethlehem", "Micah 5:2", "Matthew 2:1"], ["Born of a virgin", "Isaiah 7:14", "Matthew 1:18–23"], ["David’s lineage", "Jeremiah 23:5", "Revelation 22:16"], ["Target of murder attempt", "Jeremiah 31:15", "Matthew 2:16–18"], ["Betrayed by a friend", "Psalm 41:9", "John 13:18, 19, 26"], ["Sold for 30 silver coins", "Zechariah 11:12", "Matthew 26:14–16"], ["Crucified", "Zechariah 12:10", "John 19:16–18, 37"], ["Lots cast for His clothes", "Psalm 22:18", "Matthew 27:35"], ["No bones broken", "Psalm 34:20", "John 19:31–36"], ["Buried in a rich man’s tomb", "Isaiah 53:9", "Matthew 27:57–60"], ["Year, day, hour of His death", "Daniel 9:26, 27; Exodus 12:6", "Matthew 27:45–50"], ["Raised the third day", "Hosea 6:2", "Acts 10:38–40"],
] as const;

const summaryQuestions = [
  { n: 1, count: 4, q: "Which fulfilled prophecies confirm the Bible’s inspiration?", options: ["Cyrus would capture Babylon.", "George Washington would become president of the United States.", "Egypt would never again be a strong, leading nation.", "Morals would degenerate in the last days.", "Germany would have a 20-year drought.", "Babylon, once destroyed, would never be inhabited again."] },
  { n: 2, count: 1, q: "Jesus showed His belief in Bible inspiration by:", options: ["Talking loudly on the subject.", "Quoting from it as He taught.", "Calling fire down on those who doubted.", "Announcing it from the temple steps."] },
  { n: 3, count: 2, q: "Which scientific facts from the list below does the Bible mention?", options: ["The earth is round.", "Air has weight.", "The formula for water is “H₂O.”", "Seawater is salty."] },
  { n: 4, count: 2, q: "Which of the following health rules appear in the Bible?", options: ["Drink four gallons of water daily.", "Leave alcoholic beverages alone.", "Run every morning and evening.", "Abstain from immoral sexual conduct."] },
  { n: 5, count: 3, q: "The following statements about the Bible are true:", options: ["About 40 people helped write the Bible.", "The Bible was written over a period of 10,000 years.", "Only parts of the Bible are inspired.", "The real Bible author is the Holy Spirit.", "The Bible is a best-seller."] },
  { n: 6, count: 3, q: "Which of the following did the Bible predict about the Messiah’s life?", options: ["Would be born in Nazareth.", "Would fly to heaven often.", "Would be sold for 30 pieces of silver.", "Herod would try to kill Him.", "Would be crucified.", "Would be raised to life after seven years."] },
  { n: 7, count: 1, q: "What Bible rule, if followed, would best prevent AIDS?", options: ["Do not be sexually immoral.", "Do not worship graven images.", "Eat meals regularly."] },
  { n: 8, count: 2, q: "Which statements below are true about evolution?", options: ["It is an unproved theory.", "It undermines Christianity.", "It is a proved fact.", "It proves that human beings and apes have common ancestors.", "It is a strong tenet of communism."] },
  { n: 9, count: 5, q: "Which statements below help prove Bible inspiration?", options: ["Its biographies include bad as well as good.", "It changes the lives of its followers.", "Old Testament prophecies of the Messiah were fulfilled by Jesus.", "It predicted the rise of the four world kingdoms.", "It has astonishing unity.", "It tells the day and hour of the second coming of Jesus."] },
  { n: 10, count: 1, q: "According to the Bible God created the earth in six, literal, 24-hour days.", options: ["True", "False"] },
  { n: 11, count: 1, q: "In Noah’s day, a worldwide flood destroyed every living thing except sea life and what was inside the ark.", options: ["True", "False"] },
  { n: 12, count: 1, q: "The different languages of the world originated at the Tower of Babel.", options: ["True", "False"] },
  { n: 13, q: "I am thankful to God for giving me positive answers to life’s most puzzling questions.", options: ["Yes.", "No."] },
] as const;

function Verse({ children, reference }: { children: ReactNode; reference: string }) { return <blockquote className="af-verse">“{children}” <cite>{reference}</cite></blockquote>; }
function Question({ number, title, children }: { number: number; title: string; children: ReactNode }) { return <details className="af-question" open><summary><span>{String(number).padStart(2, "0")}</span><h2>{title}</h2><i aria-hidden>+</i></summary><div className="af-question-body">{children}</div></details>; }
function Answer({ children }: { children: ReactNode }) { return <div className="af-answer"><strong>Answer</strong><div>{children}</div></div>; }
function StudyVisual({ src, alt, portrait = false }: { src: string; alt: string; portrait?: boolean }) { return <figure className={`af-study-visual ${portrait ? "portrait" : ""}`}><Image src={src} alt={alt} width={1000} height={650} sizes="(max-width: 800px) 100vw, 760px" /></figure>; }

export default function StudyOne() {
  const { complete, setComplete } = useStudyProgress("gods-amazing-book");
  return <main className="lesson-page af-study-page pt-[82px]">
    <section className="af-hero"><div className="af-hero-image" /><div className="af-hero-shade" /><div className="shell af-hero-content"><Link className="back-link" href="/bible-studies">← All studies</Link><div className="af-guide-label"><span className="af-study-number">1</span><p className="eyebrow">Amazing Facts Study Guide</p></div><h1>Is There Anything Left<br /><em>You Can Trust?</em></h1><p>Lesson 1</p><figure className="af-cover-art"><Image src="/assets/media/images/amazing-facts-study-1/cover.jpg" alt="Original first-page cover of Amazing Facts Study Guide 1, showing a hand holding a frayed rope above a mountain valley" width={900} height={1313} priority /><figcaption>Original first page</figcaption></figure></div></section>

    <section className="shell af-introduction"><p className="eyebrow">The question of our time</p><p>In these rapidly changing and challenging times—when promises of stability and safety rarely come through; when trusted spiritual leaders prove false; when lying in politics seems to be the norm; when those you depend on the most often hurt you at the deepest—is there anything left you can trust? Yes! You can fully trust the Bible! Why? Let’s take a look at the evidence…</p></section>

    <section className="shell af-layout"><aside className="af-aside"><p className="aside-label">Complete guide</p><strong>13</strong><small>study questions</small><nav aria-label="Study contents">{Array.from({ length: 13 }, (_, i) => <a href={`#question-${i + 1}`} key={i}>Question {i + 1}</a>)}</nav></aside>
      <div className="af-questions">
        <div id="question-1"><Question number={1} title="What does the Bible claim about itself?"><Verse reference="2 Timothy 3:16">All Scripture is given by inspiration of God.</Verse><Verse reference="2 Peter 1:21">Prophecy never came by the will of man, but holy men of God spoke as they were moved by the Holy Spirit.</Verse><Verse reference="John 10:35">The Scripture cannot be broken.</Verse><Answer><p>The Bible claims to be inspired, written by men who were guided by the Holy Spirit. It says its messages cannot be broken or proved untrue.</p></Answer></Question></div>

        <div id="question-2"><Question number={2} title="How did Jesus demonstrate His confidence and belief in Scripture?"><StudyVisual src="/assets/media/images/amazing-facts-study-1/jesus-scripture.jpg" alt="Jesus holding an open Scripture scroll" /><Verse reference="Matthew 4:4, 7, 10">It is written, ‘Man shall not live by bread alone’ … It is written again, ‘You shall not tempt the LORD your God’ … For it is written, ‘You shall worship the LORD your God, and Him only you shall serve.’</Verse><Verse reference="John 17:17">Sanctify them by Your truth. Your word is truth.</Verse><Answer><p>Jesus quoted from Scripture when He was tempted by Satan. He also said the Bible is truth (John 17:17). Jesus quoted Scripture as the authority for everything He was teaching.</p></Answer></Question></div>

        <div id="question-3"><Question number={3} title="How do Bible prophecies confirm its divine inspiration?"><StudyVisual src="/assets/media/images/amazing-facts-study-1/prophecy.jpg" alt="Open Bible surrounded by scenes of kingdoms and fulfilled prophecy" /><Verse reference="Isaiah 42:8, 9">I am the LORD … New things I declare; before they spring forth I tell you of them.</Verse><Verse reference="Isaiah 46:9, 10">I am God … declaring the end from the beginning, and from ancient times things that are not yet done.</Verse><p className="af-caption">Before Cyrus was born, God’s Bible prophet named him as the general who would overthrow Babylon.</p><Answer><p>Bible predictions of future events that have come to pass dramatically confirm the divine inspiration of Scripture. These are just a few examples of fulfilled Bible prophecies:</p><ol className="af-letter-list"><li><b>Four world empires would arise:</b> Babylon, Medo-Persia, Greece, and Rome (Daniel chapters 2, 7, 8).</li><li><b>Cyrus would be the warrior who conquers Babylon</b> (Isaiah 45:1–3).</li><li><b>After Babylon’s destruction, it would never be inhabited again</b> (Isaiah 13:19, 20; Jeremiah 51:37).</li><li><b>Egypt would never again hold a commanding position among the nations</b> (Ezekiel 29:14, 15; 30:12, 13).</li><li><b>Earth-shaking calamities and increasing anxiety</b> (Luke 21:25, 26).</li><li><b>Moral degeneracy and false spirituality in the last days</b> (2 Timothy 3:1–5).</li></ol></Answer></Question></div>

        <div id="question-4"><Question number={4} title="Are the Bible’s statements about the natural world confirmed by science?"><StudyVisual src="/assets/media/images/amazing-facts-study-1/earth.jpg" alt="The earth suspended in space" portrait /><Verse reference="Psalm 119:160">The entirety of Your word is truth.</Verse><Answer><p>Yes. The Holy Spirit, who guided each Bible writer, always speaks the truth. Here are just a few Bible statements confirmed by science:</p><ol className="af-letter-list"><li><b>“He hangs the earth on nothing” (Job 26:7).</b> This scientific fact is mentioned in Job, the Bible’s oldest book.</li><li><b>“He … sits above the circle of the earth” (Isaiah 40:22).</b> The Bible said the earth is round centuries before it was confirmed by scientists.</li><li><b>“To establish a weight for the wind” (Job 28:25).</b> Long before science verified it, the Bible reported that air has weight.</li></ol></Answer></Question></div>

        <div id="question-5"><Question number={5} title="Are the Bible’s statements about health still relevant in today’s world?"><Verse reference="3 John 1:2">Beloved, I pray that you may prosper in all things and be in health, just as your soul prospers.</Verse><Answer><p>God wants His creation to be happy and healthy. Following are just a few examples of Bible health principles that confirm its divine inspiration:</p><ol className="af-letter-list"><li><b>Cover body waste with dirt (Deuteronomy 23:12, 13).</b> Moses’ command that body waste should be buried outside Israel’s encampment was thousands of years ahead of its time. When human waste is not properly disposed of, disease can quickly spread via the water supply. This Bible counsel has saved millions of lives throughout history.</li><li><b>“Nor let us commit sexual immorality” (1 Corinthians 10:8).</b> “Sexual immorality” refers to any inappropriate sexual conduct (see Leviticus 18 for a comprehensive list). By following this Bible counsel, people would have little reason to fear unwanted pregnancies or sexually transmitted diseases, such as syphilis and AIDS.</li><li><b>Leave alcoholic beverages alone (Proverbs 23:29–32).</b> If everyone followed this Bible advice, millions of alcoholics would become sober, helpful citizens; millions of broken families would be reunited; thousands of lives would be saved from drunk driving; and government and business leaders would make clear-minded decisions.</li></ol><aside className="af-note"><b>Note:</b> God not only tells us how to succeed and have joy amid today’s challenging problems, He also gives us the miraculous power to do it (1 Corinthians 15:57; Philippians 4:13; Romans 1:16). The Bible’s health principles are still relevant today and are desperately needed. (For more information, see Study Guide 13.)</aside></Answer></Question></div>

        <div id="question-6"><Question number={6} title="Are the Bible’s historical statements accurate?"><StudyVisual src="/assets/media/images/amazing-facts-study-1/archaeology.jpg" alt="Ancient pottery uncovered by archaeology" portrait /><Verse reference="Isaiah 45:19">I, the LORD, speak righteousness, I declare things that are right.</Verse><Answer><p>Yes. Sometimes evidence might not yet be available to prove certain historical claims found in Scripture, but evidence has repeatedly surfaced proving the validity of the Bible. Note the following:</p><ol className="af-letter-list"><li>For years skeptics said the Bible was unreliable because it mentions the Hittite nation (Deuteronomy 7:1) and cities like Nineveh (Jonah 1:1, 2) and Sodom (Genesis 19:1), all of which they denied ever existed. But now modern archaeology has confirmed that all three did exist.</li><li>Critics also said that the kings Belshazzar (Daniel 5:1) and Sargon (Isaiah 20:1) never existed. Again, their existence has since been confirmed.</li><li>Skeptics said the Bible record of Moses was not reliable because it mentions writing (Exodus 24:4) and wheeled vehicles (Exodus 14:25), which they said didn’t exist in his time. Today we know they did.</li><li>At one time, the 39 kings of ancient Israel and Judah were known only from the Bible record; thus, critics doubted their existence. But when archaeologists found independent ancient records that mention many of these kings, the Bible record was proved accurate once again.</li></ol><p>Critics of the Bible have been proven wrong repeatedly as new discoveries have confirmed biblical people, places, and events.</p></Answer></Question></div>

        <div id="question-7"><Question number={7} title="What other facts about the Bible prove its divine inspiration?"><div className="af-visual-pair"><StudyVisual src="/assets/media/images/amazing-facts-study-1/books-and-quill.jpg" alt="Old books, scrolls, ink, and a writing quill" /><StudyVisual src="/assets/media/images/amazing-facts-study-1/writing.jpg" alt="A writer using a quill pen" portrait /></div><Verse reference="2 Timothy 3:16">All Scripture is given by inspiration of God.</Verse><Answer><p>One of the greatest miracles of the Bible is its unity. Just ponder these amazing facts:</p><p><b>The 66 books of the Bible were written:</b></p><ul className="af-bullet-list"><li>On three continents</li><li>In three languages</li><li>By about 40 different people (such as kings, shepherds, scientists, attorneys, an army general, fishermen, priests, and a physician)</li><li>Over a period of about 1,500 years</li><li>On the most controversial subjects</li><li>By people who, in most cases, had never met</li><li>By authors whose education and background varied greatly</li></ul><p>Yet, though it seems totally inconceivable, the 66 books maintain harmony with one another. And even when new concepts on a certain subject are expressed, they do not undermine what other Bible writers say on the same subject.</p><aside className="af-note">While the four Gospels do sometimes differ in the way they report the same event, they complement rather than contradict each other.</aside><p>This is almost too amazing to believe! Ask people who have viewed the same event to give a report of what happened and you’ll discover that their stories will often differ widely and will contradict each other in some way. Yet the Bible, penned by 40 writers over a 1,500-year period, reads as if it was written by one mind. And indeed it was: “Holy men of God spoke as they were moved by the Holy Spirit” (2 Peter 1:21). The Holy Spirit moved them all. He is the real Bible author.</p></Answer></Question></div>

        <div id="question-8"><Question number={8} title="What evidence of Bible inspiration is found in the lives of people?"><div className="af-visual-pair"><StudyVisual src="/assets/media/images/amazing-facts-study-1/changed-lives.jpg" alt="People whose lives have been changed through faith and Scripture" /><StudyVisual src="/assets/media/images/amazing-facts-study-1/bible-history.jpg" alt="A thoughtful man in biblical dress" portrait /></div><Verse reference="2 Corinthians 5:17">If anyone is in Christ, he is a new creation; old things have passed away; behold, all things have become new.</Verse><Answer><p>The changed lives of those who follow Jesus and obey Scripture provide some of the most convincing proofs of the Bible’s divine inspiration. The drunk becomes sober; the immoral person becomes pure; the addicted becomes free; the profane person becomes reverent; the fearful person becomes courageous; and the cruel person becomes kind.</p></Answer></Question></div>

        <div id="question-9"><Question number={9} title="What evidence for Bible inspiration emerges when we compare Old Testament prophecies of the coming Messiah with New Testament events in the life of Jesus?"><Verse reference="Luke 24:27">Beginning at Moses and all the Prophets, [Jesus] expounded to them in all the Scriptures the things concerning Himself.</Verse><Verse reference="Acts 18:28">[Apollos] vigorously refuted the Jews publicly, showing from the Scriptures that Jesus is the Christ.</Verse><Answer><p>The Old Testament predictions of the Messiah were so specific and so clearly fulfilled by Jesus of Nazareth that both Jesus and Apollos used these prophecies to prove that Jesus was indeed the Messiah. There are more than 125 of these prophecies. Let’s review just 12 of them:</p><div className="af-table-wrap"><table><thead><tr><th>Prophecy</th><th>Old Testament Prediction</th><th>New Testament Fulfillment</th></tr></thead><tbody>{prophecies.map(([p, oldT, newT]) => <tr key={p}><td>{p}</td><td>{oldT}</td><td>{newT}</td></tr>)}</tbody></table></div><p>What are the odds that Jesus could have fulfilled just eight of these prophecies by mere chance? Dr. Peter Stoner, former chairman of the departments of mathematics, astronomy, and engineering at Pasadena College in California, applied the principle of probability to this question.</p><p>He calculated the odds of just eight being fulfilled by one man as one in 100,000,000,000,000,000.</p><p>What would be the odds of all 125 prophecies of the Messiah being fulfilled by chance alone? It simply couldn’t have happened by chance!</p><p className="af-footnote">*ScienceSpeaks.dstoner.net/Christ_of_Prophecy.html</p></Answer></Question></div>

        <div id="question-10"><Question number={10} title="What advantage does a person have who accepts the Bible as God’s inspired word?"><div className="af-visual-pair"><StudyVisual src="/assets/media/images/amazing-facts-study-1/bible-reader.jpg" alt="A young woman reading the Bible" portrait /><StudyVisual src="/assets/media/images/amazing-facts-study-1/cosmos.jpg" alt="A smiling young man beside an illustration of the cosmos" /></div><Verse reference="Psalm 119:100">I understand more than the ancients, because I keep Your precepts.</Verse><Verse reference="Psalm 119:98">You … make me wiser than my enemies.</Verse><Verse reference="Isaiah 55:9">As the heavens are higher than the earth, so are … My thoughts higher than your thoughts.</Verse><Answer><p>A person who accepts the Word of God will discover answers to many mysteries that confound those seeking only worldly answers. For instance, there is no known way life could spring up from non-life; the Bible says it took a supernatural agent—God—to start life. Scientists also now know that all human life today came from one woman; this is exactly what the Bible teaches in Genesis.</p><p>You can also know that God created the world in six, literal, 24-hour days; that a worldwide flood destroyed every living thing except sea life and what was inside the ark; and that the different world languages originated at the Tower of Babel.</p><p>God, who has always existed and knows everything, shares these truths with us in the Bible, recognizing that we could never figure them out on our own. God’s knowledge is “past finding out” (Romans 11:33). Believe the Bible, and you will always be ahead of the wisdom of mere humans.</p></Answer></Question></div>

        <div id="question-11"><Question number={11} title="What recent events have brought the power and appeal of the Bible into sharp focus?"><div className="af-visual-pair"><StudyVisual src="/assets/media/images/amazing-facts-study-1/tsunami.jpg" alt="A powerful tsunami wave approaching a city" /><StudyVisual src="/assets/media/images/amazing-facts-study-1/microscope.jpg" alt="A microscope and scientific imaging equipment" portrait /></div><Answer><p>The increasing number of natural disasters and the rise of worldwide terrorism are signs predicted by the Bible, which says that at the end of time, “On the earth distress of nations, with perplexity, the sea and the waves roaring” (Luke 21:25). The tsunami of December 26, 2004, is just one example. Over 250,000 people were reported dead or missing in what was one of the deadliest natural disasters in modern history. A year later, Hurricane Katrina ripped through New Orleans, reminding us again of the prophetic power of Jesus’ words that there would be “waves roaring.”</p><p>The Bible also predicted that “nation will rise against nation” (Matthew 24:7). After the devastating attack on the World Trade Center towers on September 11, 2001, people realized that no nation is truly secure. The ongoing conflicts in the Middle East and the ongoing torment of terrorism have brought people to the Bible as a source of strength and hope.</p><p>Some people question the Bible because it speaks of the world being created instead of “evolving.” Jesus asked, “When the Son of Man comes, will He really find faith on the earth?” (Luke 18:8). The theory of evolution, however, is now being widely discredited. For instance, molecular biology demonstrates that the single cell is irreducibly complex, making the accidental origin of life in a single cell not just improbable, but impossible.</p><p>Perhaps that’s why many former atheists now believe the world was created, including Fred Hoyle and once notorious atheist Antony Flew, who said, “The most impressive arguments for God’s existence are those that are supported by recent scientific discoveries.”</p><p>The theory of evolution teaches that humans and apes come from a common ancestor, denying that people were created in the image of God and that you have a real purpose: to live eternally with God. The scientific collapse of evolution, along with the fulfillment of Bible prophecy, can help establish your faith in the Word of God.</p></Answer></Question></div>

        <div id="question-12"><Question number={12} title="Why is the Bible your best chance for lasting happiness and peace?"><div className="af-visual-pair"><StudyVisual src="/assets/media/images/amazing-facts-study-1/bible-man.jpg" alt="A man reading the Holy Bible" portrait /><StudyVisual src="/assets/media/images/amazing-facts-study-1/bible-light.jpg" alt="A person walking toward light shining from an open Bible" portrait /></div><Verse reference="Psalm 119:105">Your word is a … light to my path.</Verse><Verse reference="John 15:11">These things I have spoken to you … that your joy may be full.</Verse><Verse reference="Genesis 1:27">In the image of God … He created them.</Verse><Verse reference="Matthew 5:16">Let your light … shine before men, that they may see your good works and glorify your Father in heaven.</Verse><Verse reference="John 14:3">I will come again and receive you to Myself; that where I am, there you may be also.</Verse><Answer><p>Because it answers life’s most puzzling and difficult questions:</p><ol className="af-letter-list"><li><b>Where did I come from?</b> God created us in His image; we are not mere accidents without purpose. We are children of God (Galatians 3:26). Even better, as His children, we are precious to Him and He desires that we be with Him forever.</li><li><b>Why am I here?</b> The Bible says our aims for life today should be to discover God’s perfect, practical answers to life’s problems, to accept Jesus’ offer of salvation from sin, and to become more like Him each day (Romans 8:29).</li><li><b>What does the future hold for me?</b> You don’t need to guess! Not only will you experience more peace and joy today, the Bible says Jesus will come very soon to take His people to the wonderful home He is preparing for them in heaven (John 14:1–3). In supreme joy and happiness, you will live forever in God’s presence (Revelation 21:3, 4).</li></ol></Answer></Question></div>

        <div id="question-13"><Question number={13} title="Are you thankful to God for lovingly answering life’s most puzzling questions?"><Answer><label className="af-your-answer">Your Answer:<input aria-label="Your answer to question 13" /></label></Answer></Question></div>

        <section className="af-faq" aria-labelledby="faq-heading"><p className="eyebrow">Your Questions Answered</p><h2 id="faq-heading">Questions readers often ask.</h2><StudyVisual src="/assets/media/images/amazing-facts-study-1/open-bible.jpg" alt="An open Bible with a red ribbon marker" /><div className="af-faq-grid">
          <article><span>01</span><h3>Why does the Bible give such awful, graphic descriptions of people’s sin?</h3><p><b>Answer:</b> Sin is horrifying to God, and He wants us to be revolted by it as much as He is. The inclusion of such stories, both the good and the bad, also gives credibility to the Bible. Telling it like it is gives people confidence that the Bible can be trusted; it doesn’t cover up anything. Satan’s strategy is to convince people they are such terrible sinners that God cannot or will not save them. What joy sweeps over them when they are shown Bible cases of people like themselves whom God delivered from sin! (Romans 15:4).</p></article>
          <article><span>02</span><h3>Is all of the Bible inspired—or just parts of it?</h3><p><b>Answer:</b> “All Scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness” (2 Timothy 3:16, emphasis added). The Bible does not merely contain the words of God—it is the Word of God. The Bible is the information and operations manual for human life. Ignore it and you will experience unnecessary difficulties.</p></article>
          <article><span>03</span><h3>Isn’t it unsafe to rely on an ancient book so far removed from our day?</h3><p><b>Answer:</b> No. The Bible’s age is one of the proofs of its inspiration. It says, “The word of the LORD endures forever” (1 Peter 1:25). The Bible stands as a rock; it cannot be destroyed. Men and even entire nations have burned, banned, and tried to discredit the Bible, but they destroyed themselves instead. Long after they were gone, the Bible remained (and remains) a bestseller in constant demand. Its message is God-given and up to date. Before you study it, pray that God opens your heart as you read.</p></article>
          <article><span>04</span><h3>Many brilliant people in the world believe no one can understand the Bible. If it is truly God’s book, shouldn’t everyone be able to understand it?</h3><p><b>Answer:</b> Bright people who can understand virtually anything else are often quickly perplexed when they read the Bible. The reason is that “spiritual things … are spiritually discerned” (1 Corinthians 2:13, 14). The deep things of the Word will never be understood by a worldly mind, no matter how brilliant. Unless one honestly seeks an experience with God, he or she cannot understand the things of God. The Holy Spirit, who explains the Bible (John 16:13; 14:26), is not understood by the secular mind. On the other hand, the humble, even uneducated, seeker who studies the Bible receives amazing understanding from the Holy Spirit (Matthew 11:25; 1 Corinthians 2:9, 10).</p></article>
          <article><span>05</span><h3>Some say the Bible is full of errors. How can anyone believe it is inspired?</h3><p><b>Answer:</b> The vast majority of so-called errors in the Bible have been demonstrated to be merely errors of judgment or a lack of understanding on the part of those who make the complaint. They are not errors at all, but simply truth misunderstood. The inspired Bible:</p><ol><li>Will always tell you the truth</li><li>Will never mislead you</li><li>Can be fully trusted</li><li>Is reliable and authoritative in spiritual, historical, and scientific matters</li></ol><p>It’s true that, in some cases, copyists might have miscopied a small word or number here and there, but no such supposed error or any other alleged error has affected the absolute truth of God’s Word. Doctrine is built not upon one Bible passage, but upon the total of divinely inspired comments on a subject. Of course, some things in the Bible are difficult to reconcile. There will always be room for doubt. However, even alleged errors not yet fully explained will eventually be reconciled, as they have been in the past. It seems the harder people work to undermine the Bible, the brighter its light shines.</p></article>
        </div></section>

        <section className="af-summary-sheet" aria-labelledby="summary-heading"><p className="eyebrow">Summary Sheet · Study Guide 1</p><h2 id="summary-heading">Review what you have learned.</h2><p>Please read this lesson before completing this Summary Sheet. All answers can be found in the Study Guide. Place a check by the correct answer. Numbers in parentheses indicate the number of correct answers.</p><div className="af-summary-grid">{summaryQuestions.map(item => <fieldset key={item.n}><legend><span>{item.n}.</span> {item.q} {"count" in item && <small>({item.count})</small>}</legend>{item.options.map(option => <label key={option}><input type="checkbox" />{option}</label>)}</fieldset>)}</div><p className="af-summary-reminder">Be sure to answer all the questions above!</p></section>

        <section className="af-source"><p className="eyebrow">Original publication</p><h2>Amazing Facts Study Guide 1</h2><p><i>Is There Anything Left You Can Trust?</i></p><p>Register here to receive your next FREE Study Guide.</p><div className="af-registration"><span>Name ____________________________________</span><span>Address __________________________________</span><span>City, State, Postcode ________________________</span></div><address>Cut along the dotted line and mail this page in an envelope to:<br /><b>Amazing Facts Oceania</b><br />PO Box 3034, Loganholme, QLD 4129<br />Phone: 0467 577 950 · Email: hello@amazingfacts.com.au</address><p className="af-copyright">*The Revised Standard Version of the Bible, copyright © 1946, 1952, 1971 by the Division of Christian Education of the National Council of the Churches of Christ in the USA. Used by permission.</p><p className="af-copyright">© 2007, 2016 Amazing Facts, Inc. All Rights Reserved. Printed by InHouse Print and Design, QLD.</p><a className="af-official-link" href="https://www.amazingfacts.com.au/bible_study/is-there-anything-left-you-can-trust-2/" target="_blank" rel="noreferrer">View the official Amazing Facts study →</a></section>

        <button className={`complete-button ${complete ? "completed" : ""}`} onClick={() => setComplete(!complete)}><span>{complete ? "✓" : "○"}</span>{complete ? "Study completed" : "Mark study as complete"}</button>
      </div>
    </section>

    <nav className="lesson-nav shell" aria-label="Study navigation"><Link href="/bible-studies"><span>←</span><small>Previous</small><b>All Bible Studies</b></Link><div className="lesson-nav-center"><span>Study 01</span><i></i><span>Study 02</span></div><Link href="/bible-studies/prophecy/daniel-2"><small>Next</small><b>God Unfolds the Future</b><span>→</span></Link></nav><Footer />
  </main>;
}
