"use client";

import Image from "next/image";
import Link from "next/link";
import { Footer } from "@/components/layout/Footer";
import { useStudyProgress } from "@/hooks/useStudyProgress";

const questions = [
  { ref: "Daniel 8:14, 8:26, 27", q: "What part of the prophecy or vision did Daniel find hard to understand?", verse: "Unto two thousand and three hundred days; then shall the sanctuary be cleansed.", answer: "Daniel wanted to understand the meaning of the 2300 days. In this Study 9 and in Study 10 we will look at this amazing time prophecy and the subject of the cleansing of God’s Heavenly sanctuary from the record of sin." },
  { ref: "Daniel 9:21–23", q: "Whom did God send to help Daniel understand this?", verse: "The man Gabriel... touched me... and said, O Daniel, I am now come forth to give thee skill and understanding.", answer: "" },
  { ref: "Daniel 9:24", q: "How much of the 2300 days was to be ‘determined’, or ‘cut off’ for Daniel’s people, the Jews?", verse: "Seventy weeks are determined upon thy people and upon thy holy city.", answer: "Ezekiel 4:6 (OT) and Numbers 14:34 (OT) indicate that in symbolic Bible prophecy a ‘day’ is used to denote a ‘year’. Thus these 2300 days actually are 2300 years of time. The 70 weeks ‘cut off’ from the major part of the prophecy for the Jews, would thus represent 490 years of time." },
  { ref: "Daniel 9:25", q: "When does this great time prophecy of 2300 years begin?", verse: "From the going forth of the commandment to restore and to build Jerusalem.", answer: "The decree to restore and build Jerusalem was given in the seventh year of the Persian King Artaxerxes in the autumn of 457 B.C. Also Ezra 6:14 (OT) tells us that there were three steps in bringing this decree about: King Cyrus in 536 B.C. originated the decree, Darius in 519 B.C. reaffirmed it and Artaxerxes completed it with a more wide ranging decree in 457 B.C. This decree of Artaxerxes is recorded in Ezra 7:7–26 (OT) and it brought the decree to the perfection required by the prophecy to mark the beginning of the 2300 years." },
  { ref: "Daniel 9:25", q: "Did Daniel foretell in this great prophecy the appearance of the Messiah (Christ)?", verse: "Unto the Messiah the Prince shall be seven weeks, and threescore and two weeks.", answer: "The Messiah was to appear ‘7 weeks and 62 weeks’ after the commencement date of the prophecy. That is 69 weeks, or 483 days (which represents 483 years), after 457 B.C. This brings us to the date 27 A.D." },
  { ref: "Luke 3:1–3, 21, 22; Acts 10:38", q: "What happened in the year 27 A.D., which according to history was the 15th year of the reign of Roman Emperor Tiberius Caesar?", verse: "Jesus also being baptized... the Holy Ghost descended in a bodily shape like a dove upon him.", answer: "The words ‘Messiah’ (Hebrew) and ‘Christ’ (Greek) mean ‘the Anointed One’. Jesus was anointed by the Holy Ghost at His baptism in 27 A.D. and remarkably Daniel foretold the exact date over 500 years in advance." },
  { ref: "Mark 1:15", q: "Did Jesus recognize the fulfilment of this prophetic time?", verse: "The time is fulfilled, and the kingdom of God is at hand.", answer: "" },
  { ref: "Daniel 9:26", q: "Was Jesus’ death foretold by the prophet?", verse: "After threescore and two weeks shall Messiah be cut off, but not for himself.", answer: "" },
  { ref: "Daniel 9:27", q: "When was this to occur?", verse: "In the midst of the week he shall cause the sacrifice and the oblation to cease.", answer: "69 weeks brought us to the ‘Messiah’. One week was left from the 70 weeks already ‘cut off’ for the Jews. One week is 7 days, or 7 actual years of time. Jesus was to be ‘cut off’ in the ‘midst’ or ‘middle’ of this week and bring the sacrificial offerings to an end. This would be 3½ years after His anointing. Jesus’ public ministry lasted 3½ years as you trace the historical record in the book of John. From the Autumn of 27 A.D. to the Spring of 31 A.D. was 3½ years. Remarkably Daniel had foretold the exact time of Jesus’ death. On the exact day of Passover in the Spring of 31 A.D., in the midst of the 70th week, at 3 pm on a Friday afternoon, Jesus cried, ‘It is finished’, and bowed His head and died, right on time.\n\nIn Romans 5:6 (NT) it says, ‘For when we were yet without strength, in due time (which means according to the time), Christ died for the ungodly.’" },
  { ref: "Daniel 9:24", q: "When was the time set aside for the Jews to end?", verse: "Seventy weeks are determined upon thy people.", answer: "69 weeks, or 483 years, brought us to Jesus’ baptism in 27 A.D. Half a week, or 3½ years, brought us to Jesus’ death in 31 A.D. Half a week, or 3½ years, brings us now to the end of the time for the Jews, 34 A.D." },
  { ref: "Acts 7:58 to 8:1", q: "Did the Jews as a nation accept Christ at that time?", verse: "They stoned Stephen... And Saul was consenting unto his death.", answer: "Stephen preached Christ to the Jews. They stoned him to death and persecuted the followers of Jesus in 34 A.D. This was the end of the 70 weeks or 490 years of probation allotted to the Jewish nation. The Jews no longer are God’s special people, but like every other person in this world, they can be saved as individuals if they accept Jesus Christ as their Saviour. Galatians 3:28, 29 (NT). No one nation any longer has any special favoured position with God." },
  { ref: "Based on what you have just read", q: "After the time ‘cut off’ for the Jewish nation, at the end of the 490 years, how much time was left to reach to the end of the 2300 years?", verse: "2300 years less 490 years leaves 1810 years. 34 A.D. + 1810 years = 1844 A.D.", answer: "2300 years less 490 years ‘cut off’ for the Jews, leaves 1810 years.\n\n34 A.D. + 1810 years = 1844 A.D.\n\nTo be exact it comes to October 22, 1844 A.D." },
  { ref: "Daniel 8:12–14", q: "What was to take place at the end of the 2300 years?", verse: "Unto two thousand and three hundred days; then shall the sanctuary be cleansed.", answer: "Two events were to take place in 1844:\n\n1. The sanctuary was to be cleansed.\n\n2. Truth was to be restored.\n\nThese two events will be explained in later studies." },
];

const paragraphs = (text: string) => text.split("\n\n").map((p) => <p key={p}>{p}</p>);

export default function StudyNine() {
  const { open, complete, setComplete, toggle } = useStudyProgress("worlds-only-hope");
  const progress = Math.round((open.length / questions.length) * 100);
  return <main className="lesson-page pt-[82px]">
    <div className="lesson-progress"><span style={{ width: `${complete ? 100 : progress}%` }} /></div>
    <section className="lesson-hero image-lesson-hero shell">
      <div className="lesson-title-row lesson-title-photo study-9-photo"><div><Link className="back-link" href="/bible-studies">← All studies</Link><p className="eyebrow">Study 09 · Prophecy</p><h1>The Most Remarkable<br /><em>Bible Prophecy</em></h1></div><div className="lesson-seal"><span>09</span><small>13 questions</small></div></div>
      <div className="lesson-intro"><p>Briefly, the vision of world history Daniel received was as follows: He saw two beasts, a ram (Medo-Persia Daniel 8:20 (OT)) and a goat (Greece Daniel 8:21 (OT)), in conflict. The ram was destroyed (the fall of Medo-Persia). Then the goat, which had a great horn (Alexander the Great) between its eyes, went through a change. The great horn was broken (Alexander died) and was replaced by four others (Alexander’s four Generals divided the Empire). Then from one of these four horns there “came forth a little horn, [the Roman Empire] which waxed exceeding great”. In Daniel 8:11, 12 (OT) we are informed that in years to come this horn power would so transform as to “cast down the truth to the ground; and it practised, and prospered”. Daniel next heard a question asked about the length of time the vision covered concerning the desolating powers previously brought to view when God’s people and sanctuary truth would be trodden down (Daniel 8:13 (OT)) and the answer came in Daniel 8:14 (OT), “Unto two thousand and three hundred days; then shall the sanctuary be cleansed”. Daniel 8:17–27 (OT) tells us that the angel Gabriel came to reveal to Daniel the meaning of this dream. He told him of the significance of the beasts and the horns, but before he could discover the meaning of the 2300 days, Daniel took sick. Over five hundred years before Jesus was born, this prophecy of Daniel 8 and 9, also actually revealed the year of His baptism, and also the year of His crucifixion. The time aspect of this prophecy will impress you, as it already has impressed thousands of other Bible students. Even sceptics and infidels have been led to believe on Christ and the Bible when confronted with this marvellous prediction.</p></div>
    </section>
    <section className="lesson-body shell"><aside className="lesson-aside"><div><p className="aside-label">Your progress</p><strong>{complete ? 100 : progress}%</strong><div className="aside-meter"><span style={{ width: `${complete ? 100 : progress}%` }} /></div><small>{complete ? "Study complete" : `${open.length} of ${questions.length} passages opened`}</small></div></aside><div className="questions">
      <div className="questions-heading"><h2>Read and study the following verses<br />and write down your answers.</h2></div>
      {questions.map((item, index) => { const isOpen = open.includes(index); return <article className={`question ${isOpen ? "open" : ""}`} key={`${item.ref}-${index}`}><button onClick={() => toggle(index)} aria-expanded={isOpen}><span className="question-index">{String(index + 1).padStart(2, "0")}</span><span className="question-main"><small>{item.ref}</small><b>{item.q}</b></span><span className="question-toggle">{isOpen ? "−" : "+"}</span></button>{item.answer && <div className="booklet-comment">{paragraphs(item.answer)}</div>}{isOpen && <div className="answer"><blockquote>“{item.verse}”</blockquote><Link className="answer-version" href="/bible-studies#why-kjv">King James Version · Why the KJV?</Link></div>}</article>; })}

      <section className="summary"><p className="eyebrow">Summary</p><p>Speaking of the end of the 2300 years in 1844, Daniel 7:10 (OT) says “the judgement was set and the books were opened”. Jesus Christ our High Priest moved from the Holy Place apartment of the Sanctuary in Heaven to the Most Holy Place apartment to begin the work of judgement. As Revelation 14:6, 7 (NT) says, “for the hour of his judgement is come”.</p><p>While it is amazing to discover how accurate the time elements of this remarkable Bible prophecy are, let us never forget the most vital part of the prophecy is found in Daniel 9:26 (OT), Messiah shall be cut off, but not for Himself. Daniel said Jesus was not to die for Himself. Nothing Jesus ever did was deserving of the cross. It was for men and women that He was “cut off”. He became our Sin-bearer.</p><p>2 Corinthians 5:21 (NT). At the cross Jesus took upon Himself the sins of the whole world. The sinless One became, in God’s sight, sin for us.</p><p>What glorious salvation, but at what a cost!</p><p>God gave His only begotten Son.</p></section>

      <section className="study-source-figure"><h3>The Prophetic Time Lines of Daniel</h3><div className="study-source-crop timeline"><Image fill sizes="(max-width: 800px) 100vw, 760px" src="/media/images/study-9-prophetic-timeline.jpeg" alt="The prophetic time lines of Daniel diagram from the study booklet" /></div><p>This diagram shows the full time of 2300 years. Commencing at 457 B.C., when the decree was given to restore and rebuild Jerusalem, seven prophetic weeks, or forty-nine years, are measured off to show the time occupied in building the wall and the city. This time, however, is a part of the sixty-nine weeks that were to reach to the Messiah. Christ was anointed, as shown in Luke 3, in A.D. 27. In the middle of the seventieth week (seven years) following, Messiah was crucified, when the sacrifices and oblations of the earthly sanctuary were to cease. Three and a half years later the Jews were rejected, and the remaining 1810 years bring us to 1844, when Christ entered the Most Holy Apartment of the Heavenly Sanctuary.</p></section>

      <section className="study-source-figure"><h3>The Sanctuary</h3><div className="study-source-crop sanctuary"><Image fill sizes="(max-width: 800px) 100vw, 760px" src="/media/images/study-9-sanctuary-plan.jpeg" alt="The sanctuary plan from the study booklet" /></div><p>The sanctuary, as built under Moses’ direction, was based upon the plan of the Heavenly Sanctuary, which he was shown whilst on Mt Sinai. It was made so as to be easily moved from place to place. The later temples, built under Solomon, and restored after the destruction of Jerusalem by Nebuchadnezzar, were permanent buildings, but built after the same order. We will consider the one built by Moses.</p><p>The sanctuary was 14m length x 4.6m breadth x 4.6m height. There was a courtyard that measured about 46m x 23m. It was surrounded by a white linen curtain forming a wall. Within this courtyard was the sanctuary, with its furniture, the altar of burnt offering, and, just before the door of the sanctuary, the laver at which the priests washed.</p><p>Within the first apartment of the sanctuary, the Holy Place, were the table of shewbread to the north, the Golden Lamp Stand with the seven lamps to the south, and the altar of incense, just before the veil. Into this apartment the priest went daily. The lights were to be kept burning continually, and the incense was to constantly ascend.</p><p>Behind the 2nd veil, in the second apartment or Most Holy Place, was a wooden chest overlaid with gold called the Ark of the Covenant. The top of the Ark was formed by the mercy seat, over which were two golden cherubim (angels) facing each other, and between which was the shekinah glory, the visible presence of God. Into this apartment only the high priest could go, and only on the Day of Atonement.</p><p>Within the ark were the two tables of stone on which was written the law of God by His own finger. Also in the ark were Aaron’s rod that bloomed (Numbers 17), and a golden pot of manna. In a pocket on the outside of the ark was a copy of the ceremonial laws.</p></section>

      <section className="tabernacle-video" aria-labelledby="tabernacle-video-title">
        <p className="eyebrow">Watch</p>
        <h3 id="tabernacle-video-title">The Tabernacle of Moses</h3>
        <div className="tabernacle-video-frame"><iframe src="https://www.youtube-nocookie.com/embed/_PAazWWJKAc?rel=0" title="The Tabernacle of Moses" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div>
      </section>
      <button className={`complete-button ${complete ? "completed" : ""}`} onClick={() => setComplete(!complete)}><span>{complete ? "✓" : "○"}</span>{complete ? "Study completed" : "Mark study as complete"}</button>
    </div></section>
    <nav className="lesson-nav shell" aria-label="Study navigation"><Link href="/bible-studies/law-and-gospel"><span>←</span><small>Previous</small><b>The Law and the Gospel</b></Link><div className="lesson-nav-center"><span>Study 08</span><i></i><span>Study 09</span></div><Link href="/bible-studies/gods-tomorrow"><small>Next</small><b>Study 10</b><span>→</span></Link></nav><Footer />
  </main>;
}
