import RevelationLectureSeries from '../lecture-series';
import { SymbolLinks } from '../symbol-guide';
import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { FiArrowLeft, FiBookOpen, FiStar, FiKey, FiSun, FiMessageSquare } from 'react-icons/fi';
import { bibleUrl, verses } from '../data';
import StoryMap from '../story-map';
export const metadata:Metadata={title:'Revelation 1 — Jesus Revealed | RevelationSigns',description:'Read Revelation 1 and explore John’s vision of Jesus, the seven lampstands, seven stars and the invitation to fear not.'};
function Passage({reference}:{reference:string}){return <a className="rv-reference" href={bibleUrl(reference)} target="_blank" rel="noreferrer">{reference} ↗<span className="rv-sr-only"> (Bible Gateway, opens in a new tab)</span></a>}
const scenes=[
 ['1–3','A message to receive','The revelation comes from God through Jesus Christ, and is communicated by an angel to John. A blessing is pronounced on those who read, hear and keep its words.','Revelation 1:1–3'],
 ['4–8','Meet the faithful witness','John greets seven churches and directs attention to Jesus: the faithful witness, risen from the dead, who loves and frees His people. His coming is announced.','Revelation 1:4–8'],
 ['9–11','John is told to write','John is on Patmos because of God’s word and the testimony of Jesus. He hears a voice and is instructed to send what he sees to seven named churches.','Revelation 1:9–11'],
 ['12–16','Jesus among the lampstands','John turns and sees a glorious figure like the Son of man among seven golden lampstands. His appearance and voice communicate majesty and power.','Revelation 1:12–16'],
 ['17–20','A hand of reassurance','John falls at His feet. Jesus tells him not to fear, identifies Himself as the One who died and lives for ever, and explains the stars and lampstands.','Revelation 1:17–20'],
];
export default function ChapterOne(){return <main>
<div className="rv-shell rv-breadcrumb"><Link href="/revelation"><FiArrowLeft/> All chapters</Link><span>Revelation 1 · Illustrated study</span></div>
<section className="rv-shell rv-study-hero"><p className="rv-eyebrow">Chapter 01 · Jesus revealed</p><h1>Before the symbols,<br/><em>meet the Saviour.</em></h1><p className="rv-lead">John’s first vision brings him face to face with the risen Jesus.<br/>His message begins with reassurance: “Fear not.”</p><div className="rv-actions"><a className="rv-button" href="#read"><FiBookOpen/> Read Revelation 1</a><a className="rv-text-link" href="#understand">Explore the vision ↓</a></div></section>
<SymbolLinks/>
<StoryMap chapter={1}/>
<section className="rv-shell"><figure className="rv-vision"><Image src="/media/images/revelation/christ-lampstands.webp" alt="Artistic illustration of the risen Jesus in a white robe with a golden sash, among separate golden lampstands" width={1536} height={1024} priority/><figcaption>An artistic illustration of Christ among the lampstands, inspired by Revelation 1:12–13. It shows selected elements, not every detail of John’s vision.</figcaption></figure></section>
<nav className="rv-study-nav rv-shell" aria-label="Chapter 1 sections"><a href="#read">Read</a><a href="#understand">Follow the scene</a><a href="#symbols">Understand the symbols</a><a href="#daniel">Connect with Daniel</a><a href="#reflect">Reflect</a></nav>
<section id="read" className="rv-shell rv-study-section"><div className="rv-section-heading"><p className="rv-eyebrow">01 · Read the passage</p><h2>Let the chapter speak first.</h2><p>Read all twenty verses. Notice what John sees, what Jesus says, and which symbols Jesus explains.</p></div><details className="rv-scripture"><summary>Open Revelation 1 <span>King James Version · 20 verses</span></summary><div>{verses.map((verse,i)=><p key={verse} id={`verse-${i+1}`}><sup>{i+1}</sup> {verse}</p>)}<p className="rv-text-credit">King James Version. <Passage reference="Revelation 1"/></p></div></details></section>
<section id="understand" className="rv-shell rv-study-section"><div className="rv-section-heading"><p className="rv-eyebrow">02 · What John sees and hears</p><h2>What happens in this chapter?</h2><p>Follow these five short steps. Each one tells you which verses to read.</p></div><div className="rv-scene-list">{scenes.map(([range,title,text,reference])=><article key={range}><span className="rv-verse-range">Verses {range}</span><div><h3>{title}</h3><p>{text}</p><Passage reference={reference}/></div></article>)}</div></section>
<section id="symbols" className="rv-paper"><div className="rv-shell rv-study-section"><div className="rv-section-heading"><p className="rv-eyebrow">03 · Understand the symbols</p><h2>Start with the explanations Jesus gives.</h2><p>A symbol is a picture that carries meaning. Some meanings are stated directly; others require comparison and interpretation.</p></div><div className="rv-symbol-grid">
<article><FiSun aria-hidden/><span className="rv-label">Explained in the chapter</span><h3>Seven golden lampstands</h3><p><strong>The seven churches.</strong> Jesus gives this explanation in verse 20. John sees Him standing among the lampstands.</p><p className="rv-application">For reflection: the scene pictures Christ present among His churches.</p><Passage reference="Revelation 1:12–13,20"/></article>
<article><FiStar aria-hidden/><span className="rv-label">Explained in the chapter</span><h3>Seven stars</h3><p><strong>The angels of the seven churches.</strong> Verse 20 identifies them, and verse 16 places the stars in His right hand.</p><details><summary>What does “angels” mean here?</summary><p>Readers differ over whether these are heavenly angels or human messengers representing the churches. Verse 20 names them as angels, without settling that question explicitly.</p></details><Passage reference="Revelation 1:16,20"/></article>
<article><FiKey aria-hidden/><span className="rv-label">Interpretation of the image</span><h3>The keys of death</h3><p>Jesus says He died and is alive for ever, and that He holds the keys of death and Hades, rendered “hell” in the KJV. Keys suggest authority: death is not beyond His power.</p><Passage reference="Revelation 1:17–18"/></article>
<article><FiMessageSquare aria-hidden/><span className="rv-label">Compare Scripture</span><h3>The sword from His mouth</h3><p>The sword belongs to the vision’s symbolic language. Comparing it with the description of God’s word as a sword helps us understand the power of Christ’s speech and judgment.</p><Passage reference="Revelation 1:16"/><Passage reference="Hebrews 4:12"/><Passage reference="Revelation 19:15"/></article>
</div><details className="rv-more"><summary>Explore the robe, white hair, eyes, feet and voice</summary><div><p>John describes a long robe and golden sash, white hair, eyes like fire, feet like glowing metal, a voice like many waters and a face like the sun. These are visionary comparisons, not an ordinary physical portrait.</p><p>Daniel 7:9 describes the Ancient of Days with white hair; Daniel 10:5–6 includes a golden belt, fiery eyes, gleaming limbs and an overwhelming voice. Reading the passages together brings their language of heavenly majesty into focus. This is a comparison of imagery, not a claim that every figure in the passages is identical.</p><Passage reference="Revelation 1:13–16"/><Passage reference="Daniel 7:9"/><Passage reference="Daniel 10:5–6"/></div></details></div></section>
<section id="daniel" className="rv-shell rv-study-section"><div className="rv-section-heading"><p className="rv-eyebrow">04 · Connect with Daniel</p><h2>Have we seen these pictures before?</h2></div><div className="rv-comparison"><article><span className="rv-eyebrow">Daniel 7:13–14</span><h3>One like the Son of man</h3><p>Daniel sees a figure like the Son of man coming with the clouds of heaven and receiving an enduring kingdom.</p><Passage reference="Daniel 7:13–14"/></article><article><span className="rv-eyebrow">Revelation 1:7, 13</span><h3>The coming and present Christ</h3><p>Revelation announces His coming with clouds, then describes one like the Son of man among the lampstands.</p><Passage reference="Revelation 1:7,13"/></article></div><aside className="rv-interpretation"><span className="rv-label">Our approach · Historicist interpretation</span><h3>How this study will connect prophecy and history</h3><p>This series will explore the historicist reading, which relates prophetic visions to the unfolding history of the church and the world. Other Christian approaches understand the timing and fulfilment differently.</p><p>In Chapter 1, we begin with the people and explanations named in the text. The seven churches are actual named communities. Reading them additionally as successive eras of church history is an interpretation; Revelation 1 does not give a dated schedule of seven eras.</p><Passage reference="Revelation 1:11,20"/></aside></section>
<section id="reflect" className="rv-shell rv-study-section"><div className="rv-section-heading"><p className="rv-eyebrow">05 · What this means for us</p><h2>“Fear not.”</h2><p>John is afraid, but Jesus reaches toward him. This chapter invites us to approach the rest of Revelation remembering who is speaking: the One who died and is alive for ever.</p><Passage reference="Revelation 1:17–18"/></div><div className="rv-questions"><details><summary>What are readers invited to do with this book?</summary><p>Read, hear and keep its message. Revelation 1:3 connects its blessing with a response in life, not only an interest in predictions.</p></details><details><summary>Which two symbols does Jesus explain directly?</summary><p>The stars are the angels of the seven churches, and the lampstands are the seven churches (Revelation 1:20).</p></details><details><summary>What gives John a reason not to fear?</summary><p>Jesus is alive for ever and holds the keys of death and Hades (Revelation 1:17–18). John can trust Jesus because He has overcome death.</p></details></div><div className="rv-reflection"><h3>A question to carry with you</h3><p>How would remembering Christ’s presence change the way you face a difficult day?</p><p><strong>A short prayer:</strong> Lord Jesus, help me hear Your voice, understand Your word and trust You as I read. Amen.</p></div></section>
<section className="rv-shell rv-next"><div><p className="rv-eyebrow">Continue the journey</p><h2>Next: Jesus speaks to His churches.</h2><p>The Chapter 2 guided study is being prepared. You can read its Bible text now.</p></div><a className="rv-button" href={bibleUrl('Revelation 2')} target="_blank" rel="noreferrer">Read Revelation 2 ↗<span className="rv-sr-only"> (opens in a new tab)</span></a></section>
<RevelationLectureSeries/>
</main>}
